name: check-dir-permission

on:
  pull_request:
    types: [opened]

jobs:
  commentSimpleComment:
    runs-on: ubuntu-latest
    name: Creating a simple comment
    steps:
      - uses: actions/checkout@v2
      - uses: foker/action-check-dir-permission@v1.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
